twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        ga_tracking: 'UA-xxxxx-x'
        uuid: '@App\Repository\FamilleRepository'